first/apps/articles/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
	#path('admin/', admin.site.urls),
	path('', views.index, name = 'index'),
	path('test/', views.test, name = 'test'),
	path('test2/', views.test2, name = 'new_test'),
	path('<int:article_id>/', views.detail, name = 'detail'),
	path('<int:article_id>/leave_comment/', views.leave_comment, name = 'leave_comment'),
	path('create/', views.create, name = 'create'),
	path('new/', views.new, name = 'new'),
	path('about_me/', views.about_me, name = 'about_me'),
	path('<int:article_id>/addlike/', views.addlike, name = "addlike"),
	path('get_all_articles/', views.get_all_articles, name = "get_all_articles"),
	path('<int:article_id>/delete/', views.delete, name = "delete"),
	path('<int:comment_id>/delete_comment/', views.delete_comment, name = "delete_comment"),
	path('<int:comment_id>/like_comment/', views.like_comment, name = "like_comment"),
	path('<int:comment_id>/add_answer/', views.add_answer, name = "add_answer"),
	path('<int:answer_id>/like_answer/', views.like_answer, name = "like_answer"),
	path('<int:answer_id>/delete_answer/', views.delete_answer, name = "delete_answer"),
	#url(r'^ajax/$', views.add_ajax)
	path('add_ajax/', views.add_ajax, name = "add_ajax"),
	path('<int:article_id>/get_json_comments/', views.get_json_comments, name = "get_json_comments")
]

first/apps/registration/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'registration'

urlpatterns = [
    path('', views.index, name = "index"),
    path('add_user', views.RegisterFormView.as_view(), name = "add_user"),
    path('validate_registration_form', views.validate_registration_form, name = "validate_registration_form")
]

first/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
'''include('apps.articles')
from apps.articles import views'''

urlpatterns = [
    path('admin', admin.site.urls),
	path('articles/', include('articles.urls')),
    path('registration/', include('registration.urls')),
    #path('registration/', views.registration, name="registration"),
    path('about_me', views.about_me, name="about_me"),
    path('accounts/', include('django.contrib.auth.urls')),
	#url(r'^polls/', include('polls.urls')),
    re_path('djga/', include('google_analytics.urls'))
]

first/apps/articles/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.postgres import fields 
''' import ArrayField'''
# Create your models here.
class Article(models.Model):
    article_title = models.CharField('article name', max_length = 100, null = True)
    article_txt = models.TextField('article text', max_length = 2000)
    pub_date = models.DateTimeField('publication date')
    comments = models.IntegerField('artcle_comments', default = 0)
    likes = models.IntegerField('likes', default = 0)
    author_name = models.CharField('article name', max_length = 100, null = True)
    views = models.BigIntegerField('views', default = 0)
    likers = models.TextField('likers', default = '')
    #likers = fields.ArrayField('likers', default = [])
    objects = models.Manager()

    '''def __init__(self):
        self.comments = len(Comment.objects.get(article_name = self.article_title))'''

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        '''now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now'''
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=3)) and self.pub_date <= timezone.now()

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE)
    author_name = models.CharField('author name', max_length = 50)
    comment_text = models.CharField('comment text', max_length = 200)
    date_pub = models.DateTimeField('comment publication date')
    answers = models.IntegerField('comment answers', default = 0)
    likes = models.IntegerField('comment likes', default = 0)
    likers = models.TextField('comment likers', default = '')
    objects = models.Manager()

    '''def __init__(self):
        self.article_name = Article.objects.get( id = self.article ).article_title'''

    '''def __str__(self):
        return self.author_name'''

    def __str__(self):
        return "Comment" + str(self.id)

class Answer(models.Model):
    text = models.TextField('answer text', max_length=200)
    author_name = models.CharField('author name', max_length = 50)
    pub_date = models.DateTimeField('answer publication date')
    comment = models.ForeignKey(Comment, on_delete = models.CASCADE)
    likes = models.IntegerField('answer likes', default = 0)
    likers = models.TextField('answer likers', default = '')
    objects = models.Manager()

    def __str__(self):
        return "Answer" + str(self.id)

class Post(models.Model):
    title = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True)
    body = models.TextField(max_length=150, db_index=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return '{}'.format(self.title)

first/apps/articles/views.py
from django.http import Http404, HttpResponseForbidden, HttpResponse, HttpResponseRedirect, JsonResponse

from django.utils import timezone

from django.urls import reverse

from django.db import models

from .models import Article, Comment, Answer

from django.shortcuts import render

import json

from django.core import serializers

import os

import hashlib

from django.views.decorators.csrf import csrf_exempt

import pymorphy2
morph = pymorphy2.MorphAnalyzer()

'''class ArticleEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, Article):
            return obj.__dict__
        return json.JSONEncoder.default(self, obj)'''

def index(request):
	latest_articles_list = Article.objects.order_by('-pub_date')
	com = {article.article_title: morph.parse('комментарий')[0].make_agree_with_number(article.comments).word for article in latest_articles_list}
	return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list, 'com': com})

def test(request):
	name = 'anton'
	name = name.encode('utf-8')
	data = str(hashlib.pbkdf2_hmac('sha256', name, os.urandom(32), 100000))
	return HttpResponse(data)

def test2(request):
	arr = ['sqqcc', 'cijppio']
	data = json.dumps(arr)
	data = json.loads(data)
	return HttpResponse(data[1])
	#return HttpResponse('I love coding')

def detail(request, article_id):
	try:
		a = Article.objects.get( id = article_id )
		a.views += 1
		a.save()
	except:
		raise Http404("Article not found")
	latest_comments_list = a.comment_set.order_by('-id')[:10]
	answers_list = Answer.objects.all()
	return render(request, 'articles/detail.html', {'article': a, 'latest_comments_list': latest_comments_list, 'json_comments_list': serializers.serialize('json', latest_comments_list), 'answers': answers_list})

def leave_comment(request, article_id):
	try:
		a = Article.objects.get( id = article_id )
		a.comments += 1
		a.save()
	except:
		raise Http404("Article not found")
	#comment = a.comment_set.create(author_name = request.user.username, comment_text = request.POST['text'], date_pub = timezone.now())
	comment = a.comment_set.create(author_name = request.user.username, comment_text = request.GET.get('text'), date_pub = timezone.now())
	comment.save()
	#return HttpResponseRedirect(reverse('articles:detail', args=(a.id,)))
	return JsonResponse({'response': 'ok'})

def get_json_comments(request, article_id):
	a = Article.objects.get(id = article_id)
	comments = a.comment_set.order_by('-id')
	return HttpResponse(serializers.serialize('json', comments))

def create(request):
	if request.user.is_authenticated:
		return render(request, 'articles/create.html')
	else:
		return HttpResponseForbidden('log in to create articles')
		#return HttpResponse('log in to create articles')

def new(request):
	#render(request, 'articles/list.html')
	art = Article(article_title = request.POST['title'], article_txt = request.POST.get('text'), pub_date = timezone.now(), author_name = request.POST.get('username'))
	art.save()
	#return HttpResponseRedirect(reverse('articles:list'))
	render(request, 'articles/list.html')
	return HttpResponseRedirect(reverse('articles:detail', args=(art.id,)))

def about_me(request):
	return render(request, 'articles/about_me.html')

def addlike(request, article_id):
	#render(request, 'articles:detail')
	#render(request, 'articles/' + str(request.POST['art_id']) + '/')
	article = Article.objects.get(id = article_id)
	likers = article.likers.split(sep = ' ')
	if request.user.is_authenticated:
		if request.user.username not in likers:
			article.likes += 1
			likers.append(request.user.username)
			likers_str = ''
			for elem in likers:
				likers_str = likers_str + elem + ' '
			article.likers = likers_str
			article.save()
		else:
			article.likes -= 1
			likers = likers[:likers.index(request.user.username)] + likers[likers.index(request.user.username) + 1:]
			likers_str = ''
			for elem in likers:
				likers_str = likers_str + elem + ' '
			article.likers = likers_str
			article.save()
	#url = 'articles/' + request.POST['art_id']
	#return render(request, 'articles/list.html')
	#return index(request)
	#return render(request, "articles/{{request.POST['art_id']}}")
	#latest_comments_list = article.comment_set.order_by('-id')[:10]
	#return render(request, 'articles/detail.html', {'article': article, 'latest_comments_list': latest_comments_list})
	return HttpResponseRedirect(reverse('articles:detail', args=(article.id,)))

def get_all_articles(request):
	all_articles = Article.objects.all()
	'''for article in all_articles:
		article = json.dumps(article, cls=ArticleEncoder)
	#data = json.dump(all_articles)
	return HttpResponse(all_articles)'''
	'''for article in all_articles:
		article = {'title': article.article_title, 'text': article.article_txt, 'author': article.author_name, 'pub_date': article.pub_date, 'comments': article.comments, 'likes': article.likes}
	#return HttpResponse(all_articles, content_type='application/json')'''
	#data = json.dumps(all_articles)
	data = serializers.serialize('json', all_articles)
	return HttpResponse(data, content_type='application/json')

def delete(request, article_id):
	article = Article.objects.get(id = article_id)
	article.delete()
	return HttpResponseRedirect('../../../articles/')

def delete_comment(request, comment_id):
	#comment = Comment.objects.get(id = request.POST['comment_id'])
	comment = Comment.objects.get(id = comment_id)
	comment.delete()
	article = Article.objects.get(id = comment.article.id)
	article.comments -= 1
	article.save()
	return HttpResponseRedirect(reverse('articles:detail', args=(article.id,)))

def like_comment(request, comment_id):
	comment = Comment.objects.get(id = comment_id)
	likers = comment.likers.split(sep = ' ')
	if request.user.is_authenticated:
		if request.user.username not in likers:
			comment.likes += 1
			likers.append(request.user.username)
			likers_str = ''
			for elem in likers:
				likers_str = likers_str + elem + ' '
			comment.likers = likers_str
			comment.save()
		else:
			comment.likes -= 1
			likers = likers[:likers.index(request.user.username)] + likers[likers.index(request.user.username) + 1:]
			likers_str = ''
			for elem in likers:
				likers_str = likers_str + elem + ' '
			comment.likers = likers_str
			comment.save()
	return HttpResponseRedirect(reverse('articles:detail', args=(comment.article.id,)))

def add_answer(request, comment_id):
	comment = Comment.objects.get(id = comment_id)
	answer = Answer(text = request.POST['answer_text'], comment = comment, author_name = request.user.username, pub_date = timezone.now())
	answer.save()
	comment.answers += 1
	comment.save()
	article = Article.objects.get(id = comment.article.id)
	article.comments += 1
	article.save()
	return HttpResponseRedirect(reverse('articles:detail', args = (article.id,)))

def like_answer(request, answer_id):
	answer = Answer.objects.get(id = answer_id)
	likers = answer.likers.split(sep = ' ')
	if request.user.is_authenticated:
		if request.user.username not in likers:
			answer.likes += 1
			likers.append(request.user.username)
			likers_str = ''
			for elem in likers:
				likers_str = likers_str + elem + ' '
			answer.likers = likers_str
			answer.save()
		else:
			answer.likes -= 1
			likers = likers[:likers.index(request.user.username)] + likers[likers.index(request.user.username) + 1:]
			likers_str = ''
			for elem in likers:
				likers_str = likers_str + elem + ' '
			answer.likers = likers_str
			answer.save()
	return HttpResponseRedirect(reverse('articles:detail', args = (Comment.objects.get(id = answer.comment.id).article.id,)))

def delete_answer(request, answer_id):
	answer = Answer.objects.get(id = answer_id)
	answer.delete()
	comment = Comment.objects.get(id = answer.comment_id)
	article = Article.objects.get(id = comment.article.id)
	comment.answers -= 1
	comment.save()
	article.comments -= 1
	article.save()
	return HttpResponseRedirect(reverse('articles:detail', args = (Comment.objects.get(id = answer.comment_id).article.id,)))

def add_ajax(request): 
	print('Hello world')
	response = {'first-text': 'Lorem Ipsum is simply dummy text', 'second-text': 'to make a type specimen book. It has '}
	return JsonResponse(response)
	#return HttpResponse('Hello world')'

'''
    if request.is_ajax():
        response = {'first-text': 'Lorem Ipsum is simply dummy text', 'second-text': 'to make a type specimen book. It has '}
        return JsonResponse(response)
    else:
        raise Http404'''

first/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.urls import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
import hashlib
import os

def about_me(request):
    return render(request, 'articles/about_me.html')

def registration(request):
    return render(request, 'registration.html')

'''hashlib.pbkdf2_hmac(hash_name='sha256',
    password=b'bad_password34',
    salt=b'bad_salt',
    iterations=100000)'''

'''def add_user(request):
    user = User(username = request.POST['username'], password = str(hashlib.pbkdf2_hmac('sha256', request.POST['password'].encode('utf-8'), os.urandom(32), 100000)))
    user.save()
    return HttpResponseRedirect(reverse('list.html'))'''

first/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    {% load template_helpers %}
    {% load bootstrap4 %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script type="text/javascript" src="{% static 'jquery.js' %}"></script>
        <!--        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>-->
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> -->
        <title>{% block title %}My site{%endblock%}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
        <script src="{% static 'script.js' %}"></script>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-164154803-1"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          
          gtag('config', 'UA-164154803-1');
        </script>

    </head>
    <body>
        <nav>
          <ul>
            <li><a href="#"><img class="img-responsive" src="https://www.leaderssl.ru/assets/getwildcard_engine/header/leadertelecom_ltd-1c8f9ca7d90e19239e7bb9a505ceeb7397064655a582eae983f1cd59d2297e6f.png" alt="Leadertelecom ltd"></a></li>
            {% if user.is_superuser %}
            <li><a href="../../../admin">Admin</a></li>
            {% endif %}
            <li><a href="../../articles/">Articles</a></li>
            <li><a href="#">Other apps</a></li>
            <li><a href="../../about_me">About me</a></li>
            <!--<li><a href="../../registration">Registration</a></li>-->
            {% if user.is_authenticated %}
            <li><a href="#" id="username">User: {{ user.get_username }}</a></li>
            <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
            {% else %}
            <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
            <li><a href="../../registration">Registration</a></li> 
            {% endif %}
            <li><a href="../../articles/get_all_articles">API</a></li>
          </ul>
        </nav>
        <br>
        {%block content%}
          <table>
            <thead>
              <tr>
                <th>Option{</th>
                <th>Default</th>
                <th>Description</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>{% block td1 %}<strong>showSpeed</strong>{% endblock %}</td>
                <td>{% block td2 %}15{% endblock %}</td>
                <td>{% block td3 %}The speed of the show/reveal{% endblock %}</td>
              </tr>
              <tr>
                <td><strong>showEasing</strong></td>
                <td>'linear'</td>
                <td>The easing of the show/reveal</td>
              </tr>
              <tr>
                <td><strong>hideSpeed</strong></td>
                <td>50</td>
                <td>The speed of the hide/conceal</td>
              </tr>
              <tr>
                <td><strong>hideEasing</strong></td>
                <td>'linear'</td>
                <td>The easing of the hide/conceal</td>
              </tr>					
              <tr>
                <td><strong>width</strong></td>
                <td>'auto'</td>
                <td>The width that the data will be truncated to - <em>('auto' or px amount)</em></td>
              </tr>
              <tr>
                <td><strong>ellipsis</strong></td>
                <td>true</td>
                <td>Set to true to enable the ellipsis</td>
              </tr>
              <tr>
                <td><strong>title</strong></td>
                <td>false</td>
                <td>Set to true to show the full data on hover</td>
              </tr>
              <tr>
                <td><strong>afterShow</strong></td>
                <td> $.noop</td>
                <td>The callback fired after the show/reveal</td>
              </tr>
              <tr>
                <td><strong>afterHide</strong></td>
                <td>$.noop</td>
                <td>The callback fired after the hide/conceal</td>
              </tr>
            </tbody>
          </table>
        {%endblock%}
    </body>
</html>

first/templates/log_in.html
{% extends 'base.html' %}

{% block title %}log in{% endblock %}

{% block content %}

{% if notfound %}
    <p>User not found</p>
{% endif %}

{% if wrong %}
    <p>Wrong password</p>
{% endif %}

<!--<form action="{% url 'registration:authorisation'%}" method="POST">

    {% csrf_token %}

    <input type="text" required placeholder="username" name="username"><br>
    <textarea name="password" required="" placeholder="password" cols="21" rows="1"></textarea><hr>
    <button type="submit">log in</button>
</form>-->
<hr>

{% endblock %}

first/templates/registration.html
{%extends 'base.html'%}

{% block title %}registration{% endblock %}

{% block content %}

<form action="{% url 'registration:add_user' %}" id="registration" method="POST">
    {% csrf_token %}
    {{form.as_p }}
    <!--<input type="text" required placeholder="username" name="username"><br>
    <textarea name="password" type="password" required="" placeholder="password" cols="21" rows="1"></textarea><hr>-->
    <a href="../"><button type="submit" class="btn btn-primary btn-lg " id="load1" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> Processing Order">Sign up</button></a>
</form>

<script>
    $(document).ready(function(){
        $('#registration').change(function(){
            //alert('Hello world');
            $.ajax({
                type: 'get',
                async: true,
                url: 'validate_registration_form',
                data: $('#registration').val(),
                success: function(data){
                    pass
                }
            });
        });
    });
</script>
<!--<a href="log_in"><button>Already have an account?</button></a>-->
<!--<form method="post" >
    {% csrf_token %}
    <table>
       {{ form.as_table }}
        <tr>
           <td></td>
           <td><input type="submit" name="submit" value="Register" /></td>
       </tr>
    </table>
</form>-->

{% endblock %}