first/apps/articles/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
	#path('admin/', admin.site.urls),
	path('', views.index, name = 'index'),
	path('test/', views.test, name = 'test'),
	path('test2/', views.test2, name = 'new_test'),
	path('<int:article_id>/', views.detail, name = 'detail'),
	path('<int:article_id>/leave_comment/', views.leave_comment, name = 'leave_comment'),
	path('create/', views.create, name = 'create'),
	path('new/', views.new, name = 'new'),
	path('about_me/', views.about_me, name = 'about_me'),
	path('<int:article_id>/addlike/', views.addlike, name = "addlike"),
	path('get_all_articles/', views.get_all_articles, name = "get_all_articles"),
	path('<int:article_id>/delete/', views.delete, name = "delete"),
	path('<int:comment_id>/delete_comment/', views.delete_comment, name = "delete_comment"),
	path('<int:comment_id>/like_comment/', views.like_comment, name = "like_comment"),
	path('<int:comment_id>/add_answer/', views.add_answer, name = "add_answer"),
	path('<int:answer_id>/like_answer/', views.like_answer, name = "like_answer"),
	path('<int:answer_id>/delete_answer/', views.delete_answer, name = "delete_answer"),
	#url(r'^ajax/$', views.add_ajax)
	path('add_ajax/', views.add_ajax, name = "add_ajax"),
	path('<int:article_id>/get_json_comments/', views.get_json_comments, name = "get_json_comments")
]

first/apps/registration/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'registration'

urlpatterns = [
    path('', views.index, name = "index"),
    path('add_user', views.RegisterFormView.as_view(), name = "add_user"),
    path('validate_registration_form', views.validate_registration_form, name = "validate_registration_form")
]

first/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
'''include('apps.articles')
from apps.articles import views'''

urlpatterns = [
    path('admin', admin.site.urls),
	path('articles/', include('articles.urls')),
    path('registration/', include('registration.urls')),
    #path('registration/', views.registration, name="registration"),
    path('about_me', views.about_me, name="about_me"),
    path('accounts/', include('django.contrib.auth.urls')),
	#url(r'^polls/', include('polls.urls')),
    re_path('djga/', include('google_analytics.urls'))
]

first/apps/articles/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.postgres import fields 
''' import ArrayField'''
# Create your models here.
class Article(models.Model):
    article_title = models.CharField('article name', max_length = 100, null = True)
    article_txt = models.TextField('article text', max_length = 2000)
    pub_date = models.DateTimeField('publication date')
    comments = models.IntegerField('artcle_comments', default = 0)
    likes = models.IntegerField('likes', default = 0)
    author_name = models.CharField('article name', max_length = 100, null = True)
    views = models.BigIntegerField('views', default = 0)
    likers = models.TextField('likers', default = '')
    #likers = fields.ArrayField('likers', default = [])
    objects = models.Manager()

    '''def __init__(self):
        self.comments = len(Comment.objects.get(article_name = self.article_title))'''

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        '''now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now'''
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=3)) and self.pub_date <= timezone.now()

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE)
    author_name = models.CharField('author name', max_length = 50)
    comment_text = models.CharField('comment text', max_length = 200)
    date_pub = models.DateTimeField('comment publication date')
    answers = models.IntegerField('comment answers', default = 0)
    likes = models.IntegerField('comment likes', default = 0)
    likers = models.TextField('comment likers', default = '')
    objects = models.Manager()

    '''def __init__(self):
        self.article_name = Article.objects.get( id = self.article ).article_title'''

    '''def __str__(self):
        return self.author_name'''

    def __str__(self):
        return "Comment" + str(self.id)

class Answer(models.Model):
    text = models.TextField('answer text', max_length=200)
    author_name = models.CharField('author name', max_length = 50)
    pub_date = models.DateTimeField('answer publication date')
    comment = models.ForeignKey(Comment, on_delete = models.CASCADE)
    likes = models.IntegerField('answer likes', default = 0)
    likers = models.TextField('answer likers', default = '')
    objects = models.Manager()

    def __str__(self):
        return "Answer" + str(self.id)

class Post(models.Model):
    title = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True)
    body = models.TextField(max_length=150, db_index=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return '{}'.format(self.title)

first/apps/articles/views.py
from django.http import Http404, HttpResponseForbidden, HttpResponse, HttpResponseRedirect, JsonResponse

from django.utils import timezone

from django.urls import reverse

from django.db import models

from .models import Article, Comment, Answer

from django.shortcuts import render

import json

from django.core import serializers

import os

import hashlib

from django.views.decorators.csrf import csrf_exempt

import pymorphy2
morph = pymorphy2.MorphAnalyzer()

'''class ArticleEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, Article):
            return obj.__dict__
        return json.JSONEncoder.default(self, obj)'''

def index(request):
	latest_articles_list = Article.objects.order_by('-pub_date')
	com = {article.article_title: morph.parse('комментарий')[0].make_agree_with_number(article.comments).word for article in latest_articles_list}
	return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list, 'com': com})

def test(request):
	name = 'anton'
	name = name.encode('utf-8')
	data = str(hashlib.pbkdf2_hmac('sha256', name, os.urandom(32), 100000))
	return HttpResponse(data)

def test2(request):
	arr = ['sqqcc', 'cijppio']
	data = json.dumps(arr)
	data = json.loads(data)
	return HttpResponse(data[1])
	#return HttpResponse('I love coding')

def detail(request, article_id):
	try:
		a = Article.objects.get( id = article_id )
		a.views += 1
		a.save()
	except:
		raise Http404("Article not found")
	latest_comments_list = a.comment_set.order_by('-id')[:10]
	answers_list = Answer.objects.all()
	return render(request, 'articles/detail.html', {'article': a, 'latest_comments_list': latest_comments_list, 'json_comments_list': serializers.serialize('json', latest_comments_list), 'answers': answers_list})

def leave_comment(request, article_id):
	try:
		a = Article.objects.get( id = article_id )
		a.comments += 1
		a.save()
	except:
		raise Http404("Article not found")
	#comment = a.comment_set.create(author_name = request.user.username, comment_text = request.POST['text'], date_pub = timezone.now())
	comment = a.comment_set.create(author_name = request.user.username, comment_text = request.GET.get('text'), date_pub = timezone.now())
	comment.save()
	#return HttpResponseRedirect(reverse('articles:detail', args=(a.id,)))
	return JsonResponse({'response': 'ok'})

def get_json_comments(request, article_id):
	a = Article.objects.get(id = article_id)
	comments = a.comment_set.order_by('-id')
	return HttpResponse(serializers.serialize('json', comments))

def create(request):
	if request.user.is_authenticated:
		return render(request, 'articles/create.html')
	else:
		return HttpResponseForbidden('log in to create articles')
		#return HttpResponse('log in to create articles')

def new(request):
	#render(request, 'articles/list.html')
	art = Article(article_title = request.POST['title'], article_txt = request.POST.get('text'), pub_date = timezone.now(), author_name = request.POST.get('username'))
	art.save()
	#return HttpResponseRedirect(reverse('articles:list'))
	render(request, 'articles/list.html')
	return HttpResponseRedirect(reverse('articles:detail', args=(art.id,)))

def about_me(request):
	return render(request, 'articles/about_me.html')

def addlike(request, article_id):
	#render(request, 'articles:detail')
	#render(request, 'articles/' + str(request.POST['art_id']) + '/')
	article = Article.objects.get(id = article_id)
	likers = article.likers.split(sep = ' ')
	if request.user.is_authenticated:
		if request.user.username not in likers:
			article.likes += 1
			likers.append(request.user.username)
			likers_str = ''
			for elem in likers:
				likers_str = likers_str + elem + ' '
			article.likers = likers_str
			article.save()
		else:
			article.likes -= 1
			likers = likers[:likers.index(request.user.username)] + likers[likers.index(request.user.username) + 1:]
			likers_str = ''
			for elem in likers:
				likers_str = likers_str + elem + ' '
			article.likers = likers_str
			article.save()
	#url = 'articles/' + request.POST['art_id']
	#return render(request, 'articles/list.html')
	#return index(request)
	#return render(request, "articles/{{request.POST['art_id']}}")
	#latest_comments_list = article.comment_set.order_by('-id')[:10]
	#return render(request, 'articles/detail.html', {'article': article, 'latest_comments_list': latest_comments_list})
	return HttpResponseRedirect(reverse('articles:detail', args=(article.id,)))

def get_all_articles(request):
	all_articles = Article.objects.all()
	'''for article in all_articles:
		article = json.dumps(article, cls=ArticleEncoder)
	#data = json.dump(all_articles)
	return HttpResponse(all_articles)'''
	'''for article in all_articles:
		article = {'title': article.article_title, 'text': article.article_txt, 'author': article.author_name, 'pub_date': article.pub_date, 'comments': article.comments, 'likes': article.likes}
	#return HttpResponse(all_articles, content_type='application/json')'''
	#data = json.dumps(all_articles)
	data = serializers.serialize('json', all_articles)
	return HttpResponse(data, content_type='application/json')

def delete(request, article_id):
	article = Article.objects.get(id = article_id)
	article.delete()
	return HttpResponseRedirect('../../../articles/')

def delete_comment(request, comment_id):
	#comment = Comment.objects.get(id = request.POST['comment_id'])
	comment = Comment.objects.get(id = comment_id)
	comment.delete()
	article = Article.objects.get(id = comment.article.id)
	article.comments -= 1
	article.save()
	return HttpResponseRedirect(reverse('articles:detail', args=(article.id,)))

def like_comment(request, comment_id):
	comment = Comment.objects.get(id = comment_id)
	likers = comment.likers.split(sep = ' ')
	if request.user.is_authenticated:
		if request.user.username not in likers:
			comment.likes += 1
			likers.append(request.user.username)
			likers_str = ''
			for elem in likers:
				likers_str = likers_str + elem + ' '
			comment.likers = likers_str
			comment.save()
		else:
			comment.likes -= 1
			likers = likers[:likers.index(request.user.username)] + likers[likers.index(request.user.username) + 1:]
			likers_str = ''
			for elem in likers:
				likers_str = likers_str + elem + ' '
			comment.likers = likers_str
			comment.save()
	return HttpResponseRedirect(reverse('articles:detail', args=(comment.article.id,)))

def add_answer(request, comment_id):
	comment = Comment.objects.get(id = comment_id)
	answer = Answer(text = request.POST['answer_text'], comment = comment, author_name = request.user.username, pub_date = timezone.now())
	answer.save()
	comment.answers += 1
	comment.save()
	article = Article.objects.get(id = comment.article.id)
	article.comments += 1
	article.save()
	return HttpResponseRedirect(reverse('articles:detail', args = (article.id,)))

def like_answer(request, answer_id):
	answer = Answer.objects.get(id = answer_id)
	likers = answer.likers.split(sep = ' ')
	if request.user.is_authenticated:
		if request.user.username not in likers:
			answer.likes += 1
			likers.append(request.user.username)
			likers_str = ''
			for elem in likers:
				likers_str = likers_str + elem + ' '
			answer.likers = likers_str
			answer.save()
		else:
			answer.likes -= 1
			likers = likers[:likers.index(request.user.username)] + likers[likers.index(request.user.username) + 1:]
			likers_str = ''
			for elem in likers:
				likers_str = likers_str + elem + ' '
			answer.likers = likers_str
			answer.save()
	return HttpResponseRedirect(reverse('articles:detail', args = (Comment.objects.get(id = answer.comment.id).article.id,)))

def delete_answer(request, answer_id):
	answer = Answer.objects.get(id = answer_id)
	answer.delete()
	comment = Comment.objects.get(id = answer.comment_id)
	article = Article.objects.get(id = comment.article.id)
	comment.answers -= 1
	comment.save()
	article.comments -= 1
	article.save()
	return HttpResponseRedirect(reverse('articles:detail', args = (Comment.objects.get(id = answer.comment_id).article.id,)))

def add_ajax(request): 
	print('Hello world')
	response = {'first-text': 'Lorem Ipsum is simply dummy text', 'second-text': 'to make a type specimen book. It has '}
	return JsonResponse(response)
	#return HttpResponse('Hello world')'

'''
    if request.is_ajax():
        response = {'first-text': 'Lorem Ipsum is simply dummy text', 'second-text': 'to make a type specimen book. It has '}
        return JsonResponse(response)
    else:
        raise Http404'''

first/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.urls import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
import hashlib
import os

def about_me(request):
    return render(request, 'articles/about_me.html')

def registration(request):
    return render(request, 'registration.html')

'''hashlib.pbkdf2_hmac(hash_name='sha256',
    password=b'bad_password34',
    salt=b'bad_salt',
    iterations=100000)'''

'''def add_user(request):
    user = User(username = request.POST['username'], password = str(hashlib.pbkdf2_hmac('sha256', request.POST['password'].encode('utf-8'), os.urandom(32), 100000)))
    user.save()
    return HttpResponseRedirect(reverse('list.html'))'''

first/templates/articles/about_me.html
{%extends 'base.html'%}

{% block title %}About me{% endblock %}
{% load static %}
{% block content %}
    <h2 align="center">My name is Anton I'm 17 and I learn python</h2>
    <iframe src="{% static 'vid.mp4' %}" frameborder="0"></iframe>
{% endblock %}

first/templates/articles/create.html
{%extends 'base.html'%}

{%block title%}create{%endblock%}

{% block content %}

{% if user.is_authenticated %}
<form action="{% url 'articles:new' %}" method="POST">

    {% csrf_token %}
    <input type="hidden" name="username" value="{{user.get_username}}" readonly><br>
    <input type="text" required placeholder="article title" name="title"><br>
    <textarea name="text" required="" placeholder="article text" cols="30" rows="10"></textarea><hr>
    <div style="margin:3em;">
        <button type="submit" class="btn btn-primary btn-lg " id="load1" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> Processing Order">Add article</button>
    </div>
</form>
{% else %}
<p>log in to create articles</p>
{% endif %}

{% endblock %}

first/templates/articles/detail.html
{%extends 'base.html'%}

{%block title%}{{ article.article_title }}{%endblock%}

{% load static %}

{%block content%}
<h2>{{article.article_title}}</h1>
<p>{{article.article_txt}}</p>
<em>{{article.pub_date}}</em><br>
<em>author: {{article.author_name}}</em><br>
{% if article.was_published_recently %}
    NEW!
{%endif%}
<p>views: {{article.views}}</p>

{% if user.username == article.author_name or user.is_superuser%}
    <form action="{% url 'articles:delete' article.id %}">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>
{% endif %}

<hr>

{% if latest_comments_list %}
    <div id="comments">
        {% for comment in latest_comments_list %}
             <em>{{ comment.author_name }}</em><br>
             {{comment.comment_text}}
             {% if user.username == comment.author_name or user.is_superuser %}
                <form action="{% url 'articles:delete_comment' comment.id %}" method="POST">
                    {% csrf_token %}
                    <!--<input type="hidden" value="{{comment.id}}" name="comment_id" readonly><br>-->
                    <button type="submit">Delete comment</button>
                </form>
             {% endif %}
             <form action="{% url 'articles:like_comment' comment.id %}" method="POST">
                {% csrf_token %}
                <!--<input type="hidden" value="{{comment.id}}" name="comment_id" readonly><br>-->
                <button type="submit">Like {{ comment.likes }}</button>
            </form>
            {% for answer in answers %}
                {% if answer.comment_id == comment.id %}
                    <div style="margin:3em;">
                        <p>Author: {{ answer.author_name }}</p>
                        <p>{{ answer.text }}</p>
                        <form action="{% url 'articles:like_answer' answer.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit">Like {{ answer.likes }}</button>
                        </form>
                    </div>
                {% endif %}
                {% if user.username == answer.author_name or user.is_superuser %}
                    <div style="margin:3em;">
                        <form action="{% url 'articles:delete_answer' answer.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit">Delete answer</button>
                        </form>
                    </div>
                {% endif %}
            {% endfor %}
            {% if user.is_authenticated %}
                <form action="{% url 'articles:add_answer' comment.id%}" method="POST">
                    {% csrf_token %}
                    <textarea name="answer_text" id="" name="answer_text" placeholder="answer text" cols="20" rows="1"></textarea>
                    <button type="submit">Leave answer</button>
                </form>
            {% endif %}
         <br>
        {% endfor %}
    </div>
{% else %}
    <p>
        <em>No comments</em>
    </p>

{% endif %}

<form action="{% url 'articles:addlike' article.id %}" method="POST">

    {% csrf_token %}

    <!--<input type="hidden" value="{{article.id}}" name="art_id">-->
    <button type="submit"><p><img height="20px" src="{% static 'like.jpeg' %}" alt="like">{{ article.likes }}</p></button>

</form>

<hr>

{% if user.is_authenticated %}
<!-- <form action="{% url 'articles:leave_comment' article.id %}" method="POST"> -->
<form action="">
    {% csrf_token %}

    <!--<input type="hidden" value="{{user.get_username}}" name="name" readonly><br>-->
    <textarea name="text" id="comment_text" required="" placeholder="comment text" cols="30" rows="10"></textarea><br>
    <div style="margin:3em;">
        <button id="leave_comment" class="btn btn-primary btn-lg " id="load1" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> Processing Order">Leave comment</button>
    </div>
</form>
<hr>
{% else %}
<p>log in to leave comments</p>
{% endif %}

<div style="margin:3em;">
    <a href="../"><button class="btn btn-primary btn-lg " id="load1" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> Processing Order">All articles</button></a>
</div>
<script>
    var comments;
    $(document).ready(function(){
        $.ajax({
            type: 'GET',
            async: true,
            url: 'get_json_comments/',
            dataType: 'json',
            success: function(data){
                comments = data;
                try{
                    alert(comments);
                }catch(e){
                    alert(e);
                }
            }
        });
        comments.array.forEach(element => {
            try{
                alert(Element);
            }catch(e){
                alert(e);
            }
        });
        $('#leave_comment').click(function(){
            /*try{
                alert(JSON.parse(json_comments_list));
            }catch(e){
                alert(e);
            }*/
            $.ajax({
                type: 'GET',
                async: true,
                url: 'leave_comment/',
                data: {text: $('#comment_text').val()},
                dataType: 'json',
                success: function(data){
                    if(data['response'] == 'ok'){
                        //alert(JSON.parse(json_comments_list));
                        try{
                            $('#comments').load("{% url 'articles:detail' article.id %} #comments");
                        }catch(e){
                            alert(e);
                        }
                    }else{
                        alert('failed');
                    }
                },
                error: function(){
                    alert('error');
                }
            });
        });
    });
</script>

{%endblock%}

first/templates/articles/list.html
{%extends 'base.html'%}

{%block title%}recent articles{%endblock%}

{%block content%}
    {% load template_helpers %}
    <table id="table">
        <thead>
            <tr>
                <th>articles</th> 
                <th>comments</th> 
                <th>was published</th>
            </tr>
        </thead>
        <tbody>
            {% if latest_articles_list %}
                {% for a in latest_articles_list %}
                    <tr>
                        <td><a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a></td>
                        <td>{{a.comments}}</td>
                        <td>{{a.pub_date}}</td>
                    </tr> 
                {% endfor %}
            {% endif %}
        </tbody>
    </table>
    <!--<form action="{% url 'articles:create' %}" method="POST">

        {% csrf_token %}
    
        <input type="text" required placeholder="article title" name="title"><br>
        <textarea name="text" required="" placeholder="article text" cols="30" rows="10"></textarea><hr>
        <button type="submit">add article</button>
    </form>-->
    <div style="margin:3em;">
        <a href="create"><button class="btn btn-primary btn-lg " id="load1" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> Processing Order">Create</button></a>
    </div>
    <!--<img src="https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/55/556ad181c830e2af2deca1e80e97a8ec191e88d4_full.jpg" alt="lefrut" width="500">-->
    <a href="#" id="ajax-text-me">ajax</a>
    <div id="more-text-here1"></div>
    <div id="more-text-here2"></div>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#ajax-text-me").click(function() {
                alert('Hello world');
                //$("#more-text-here1").text('l;;kk');
                $.ajax({
                    type: 'GET',
                    async: true,
                    url: 'add_ajax',//"{% url 'articles:add_ajax' %}"
                    //data: 'data',
                    //data: query,//data: "param1=value1&param2=value2;",
                    dataType: 'json',
                    success: function(data) {
                        alert('ok');
                        $("#more-text-here1").append(data['first-text']);
                        $("#more-text-here2").append(data['second-text']);
    
                    },
                    error: function(){
                        alert('not ok')
                    }
                    //processData: boolean(true)
                });
                /*$.get("add_ajax", function(data) {
                    alert(data);
                }, 'text');*/
                /*$.get(
                    "/add_ajax",
                    function(data){
                        alert(data);
                    },
                    text
                    );*/
                
                /*function onAjaxSuccess(data)
                {
                // Здесь мы получаем данные, отправленные сервером и выводим их на экран.
                alert(data);
                }*/
            });
        });
    </script>    
{%endblock%}